CREATE DATABASE PRANAV;
USE PRANAV;
CREATE TABLE NEEDS(
    id INT PRIMARY KEY,
    Soap VARCHAR(50),

);
INSERT INTO PRANAV VALUES(1,"MYSORE SOAP")
INSERT INTO PRANAV VALUES(2,"MARGO")
SELECT * FROM PRANAV
